// Regenerates packages/shared/src/abi.ts from the Foundry artifacts in contracts/out.
// Run `cd contracts && forge build` first. Usage: node scripts/gen-abi.mjs [--check]
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(new URL(".", import.meta.url).pathname, "..");
const out = resolve(root, "contracts/out");
const target = resolve(root, "packages/shared/src/abi.ts");
const ccaSrc = resolve(root, "contracts/lib/continuous-clearing-auction/src");

// export key -> [artifact path under contracts/out, contract name]
const sources = {
  cardVault: ["CardVault.sol", "CardVault"],
  bidGateHook: ["BidGateHook.sol", "BidGateHook"],
  cardNames: ["CardNames.sol", "CardNames"],
  ccaAuction: ["ICCA.sol", "ICCAAuction"],
  ccaFactory: ["ICCA.sol", "ICCAFactory"],
  shardToken: ["ShardToken.sol", "ShardToken"],
  shardMarket: ["IShardMarket.sol", "IShardMarket"],
  erc20: ["IERC20Metadata.sol", "IERC20Metadata"],
  permit2: ["ICCA.sol", "IPermit2"],
  ensResolver: ["IENSv2.sol", "IENSResolverV2"],
  ensRegistry: ["IENSv2.sol", "IENSRegistryV2"],
};

// ICCA.sol is a minimal interface; the deployed auctions are upstream CCA v2.1.0 and also emit and revert with these.
// They are single-line declarations upstream, so they are lifted verbatim from the pinned submodule sources.
const ccaUpstreamFiles = [
  "interfaces/IContinuousClearingAuction.sol",
  "interfaces/IAuctionStorage.sol",
  "interfaces/IBidStorage.sol",
  "interfaces/ICheckpointStorage.sol",
  "interfaces/IStepStorage.sol",
  "interfaces/ITickStorage.sol",
  "libraries/ValidationHookLib.sol",
];

function readArtifact([file, name]) {
  const p = resolve(out, file, `${name}.json`);
  if (!existsSync(p)) throw new Error(`missing artifact ${p}; run \`cd contracts && forge build\``);
  return JSON.parse(readFileSync(p, "utf8")).abi.filter((i) => ["function", "event", "error"].includes(i.type));
}

const canonical = (t) => (t.type.startsWith("tuple") ? `(${t.components.map(canonical).join(",")})${t.type.slice(5)}` : t.type);
const key = (i) => `${i.type} ${i.name}(${i.inputs.map(canonical).join(",")})`;

function parseParams(s) {
  if (!s.trim()) return [];
  return s.split(",").map((raw) => {
    const parts = raw.trim().split(/\s+/);
    const type = parts[0];
    if (!/^(u?int\d*|address|bool|bytes\d*|string)(\[\d*\])*$/.test(type)) throw new Error(`unsupported upstream type ${type}`);
    const indexed = parts.includes("indexed");
    const name = parts.length > 1 && parts[parts.length - 1] !== "indexed" ? parts[parts.length - 1] : "";
    return { name, type, indexed };
  });
}

function upstreamCcaItems() {
  const items = [];
  for (const f of ccaUpstreamFiles) {
    const src = readFileSync(resolve(ccaSrc, f), "utf8");
    for (const m of src.matchAll(/^\s*(event|error)\s+(\w+)\s*\(([^)]*)\)\s*;/gm)) {
      const [, type, name, params] = m;
      const inputs = parseParams(params).map((p) => (type === "event" ? p : { name: p.name, type: p.type }));
      items.push(type === "event" ? { type, name, inputs, anonymous: false } : { type, name, inputs });
    }
  }
  return items;
}

const abis = {};
for (const [k, src] of Object.entries(sources)) abis[k] = readArtifact(src);

const seen = new Set(abis.ccaAuction.map(key));
for (const item of upstreamCcaItems()) {
  if (!seen.has(key(item))) {
    seen.add(key(item));
    abis.ccaAuction.push(item);
  }
}

const lines = [
  "// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand; run `cd contracts && forge build && cd .. && node scripts/gen-abi.mjs`.",
  "",
];
for (const [k, items] of Object.entries(abis)) {
  lines.push(`export const ${k}Abi = ${JSON.stringify(items, null, 2)} as const;`, "");
}
lines.push(`export const abi = { ${Object.keys(abis).map((k) => `${k}: ${k}Abi`).join(", ")} } as const;`, "");
const text = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== text) {
    console.error("packages/shared/src/abi.ts is out of date; run node scripts/gen-abi.mjs");
    process.exit(1);
  }
  console.log("abi.ts is up to date");
} else {
  writeFileSync(target, text);
  console.log(`wrote ${target} (${Object.entries(abis).map(([k, v]) => `${k}:${v.length}`).join(" ")})`);
}
